apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: go-app
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      app: go-app
  podMetricsEndpoints:
    - port: "2112"
